---
- name: Setup Minecraft SErver
  hosts: all
  become: yes

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Java 21
      apt:
        name: openjdk-21-jre-headless
        state: present
    
    - name: Verify Java Installation
      command: java -version
      register: java_version

    - name: Display Java version
      debug:
        msg: "Java installed: {{ java_version.stderr_lines[0] }}"
